Update prettier.yml
Signed-off-by: Cody Olsen <stipsan@gmail.com>

diff --git a/.github/workflows/prettier.yml b/.github/workflows/prettier.yml
--- a/.github/workflows/prettier.yml
+++ b/.github/workflows/prettier.yml
@@ -1,25 +1,35 @@
-name: 🤖 Auto Prettier ✨
+---
+name: Prettier
 
-on: push
+on:
+  push:
+    branches: [main]
+  workflow_dispatch:
 
 concurrency:
-  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
+  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
   cancel-in-progress: true
 
 jobs:
   run:
-    name: Prettier if needed
+    name: 🤔
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
+      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
       - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
         with:
           cache: npm
           node-version: lts/*
-      - run: npm ci --no-scripts
+      - run: npm ci --ignore-scripts --only-dev
+      - uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3
+        with:
+          path: node_modules/.cache/prettier/.prettier-cache
+          key: prettier-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.gitignore') }}
       - name: check if workflows needs prettier
-        run: npx prettier --ignore-path .gitignore --check ".github/workflows/**/*.yml" || (echo "An action can't make changes to actions, you'll have to run prettier manually" && exit 1)
-      - run: npx prettier --ignore-path .gitignore --write .
+        run: npx prettier --cache --check ".github/workflows/**/*.yml" || (echo "An action can't make changes to actions, you'll have to run prettier manually" && exit 1)
+      - run: npx prettier --ignore-path .gitignore --cache --write .
       - uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b # tag=v9
         with:
-          message: 'chore(bot): prettier --write [skip release]'
+          default_author: github_actions
+          commit: --no-verify
+          message: 'chore(prettier): 🤖 ✨'
